#!/bin/bash

# Edit Apt Sources.list configuration file
cd /etc/apt
rm sources.list
touch sources.list
echo "#Regular repositories" >> sources.list
echo "deb http://http.kali.org/kali sana main non-free contrib" >> sources.list
echo "deb http://security.kali.org/kali-security sana/updates main contrib non-free" >> sources.list
echo " Source Repositories" >> sources.list
echo "deb-src http://http.kali.org/kali sana main non-free contrib" >> sources.list
echo "deb-src http://security.kali.org/kali-security sana/updates main contrib non-free" >> sources.list

# Return to /root
cd

# Update and Install Software from Apt Sources

apt-get clean -y && apt-get update -y && apt-get upgrade -y && apt-get dist-upgrade -y

apt-get install linux-headers-$(uname -r)

apt-get install git

# Virtual Machines
apt-get install dkms

apt-get build-deps virtualbox

apt-get install virtualbox

apt-get install virtualbox-dkms

# Zsh
apt-get build-deps zsh
apt-get install zsh

# Vim
apt-get build-deps vim
apt-get install vim

# Tor (Does not include Tor-Browser-Bundle)
apt-get build-deps tor
apt-get install tor

# I3 Window Manager
apt-get build-deps i3
apt-get install i3

# Graphical File Manager for I3 Window Manager
apt-get build-deps thunar
apt-get install thunar

# Audio Control
# TODO Makesure this is spelled correctly.
apt-get build-deps pulseaudio
apt-get install pulseaudio

# TODO Makesure this is spelled correctly.
apt-get build-deps pavucontrol
apt-get install pavucontrol

# Graphical Network Manager for use in I3 Window Manager
# To use > $wicd-gtk
apt-get build-deps wicd
apt-get install wicd


# Install sp13 Version of VIM
curl https://j.mp/spf13-vim3 -L > spf13-vim.sh && sh spf13-vim.sh

# Return to /root
cd

# Install Oh-my-Zsh
sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

# Return to /root
cd

# Change default Zsh theme to amuse theme
sed -i -e s/"robbyrussell"/"amuse"/g .zshrc

# Add my preferred plugins for Zsh
sed -i -e s/plugins=(git )/plugins=(git catimg common-aliases compleat debian fasd python vi-mode web-searcha wd )/g .zshrc

# TODO upload all scripts to github to download my personal scripts

# TODO script to configure I3 Window Manager

# TODO set I3 Window Manager to default X Session

# TODO set Desktop Background in I3 Window Manager

# TODO Download and Install Tor-Browser-Bundle

#{ 
GIT HUB REPO
https://github.com/bcoffey218/Scripts-Configs.git
}





